### ISSUE TITLE
form with all required fields

### ISSUE THREAD

**Issue by Sushanthbc** [Sushanthbc/dozer_app#3]
EPIC #2 

So for starters, you don't even worry about getting how things look like in MOCK UP.

All you have to do is create a form which makes POST request, it's completely okay drop all fields in just one view - 

https://docs.flutter.io/flutter/widgets/Form-class.html
https://medium.com/@anilcan/forms-in-flutter-6e1364eafdb5

**Comment by kslo88** [comment]
Just an update. I have finished adding all the required fields to the screen and formed a sample request body for POST. Now I'm working on adding validation for the required fields.
